name: mera_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_sidemenu: ^0.7.1
  provider: ^6.1.5+1
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  image_picker: ^1.1.2
  cloud_firestore: ^6.0.1
  http: ^1.5.0
  speech_to_text: ^7.3.0
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
